### ISSUE TITLE
Please, add source file for quilt package.

### ISSUE THREAD

**Issue by faunris** [vir/sangoma-wanpipe-deb#1]
Привет. Думаю могу писать на русском.

Если я все правильно понял для сборки вашего форка ята, надо собрать этот пакет. Но к сожалению вы не добавили апстримный сорс файл.
Формат сорса должен быть например как:
wanpipe_7.0.16.orig.tar.gz
Вот ссылка для скачивания:
ftp://ftp.sangoma.com/linux/current_wanpipe/wanpipe-7.0.16.tgz

И еще вопрос. Не будет ли asterisk и asterisk-dahdi, каким либо образом конфликтовать с этим пакетом?

**Comment by vir** [comment]
Можно выкинуть зависимость на него из control в yate и всё соберётся без поддержки wanpipe.
Если честно, пакет получился кривоват. Ещё до ума доводить и доводить. Но сейчас как-то не до этого :(
Насчёт астериска не представляю, я пакет делал "для себя" и довольно спешно, никаких исследований не проводил.
